CREATE SEQUENCE USER_SEQ
  START WITH   1
  INCREMENT BY 50
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE SHARED_RESPONSE_CACHE_SEQ
  START WITH   1
  INCREMENT BY 50
  NOCACHE
  NOCYCLE;

CREATE SCHEMA FRAMEWORK_DEMO AUTHORIZATION sa;

CREATE TABLE FRAMEWORK_DEMO.SHARED_RESPONSE_CACHE
(
  ID      BIGINT NOT NULL,
  UUID    CHAR(36),
  HEADERS VARCHAR(512),
  BODY    CLOB,
  PRIMARY KEY (ID)
);

CREATE TABLE FRAMEWORK_DEMO.USER
(
  ID         BIGINT NOT NULL,
  FIRST_NAME VARCHAR(64),
  LAST_NAME  VARCHAR(64),
  USERNAME   VARCHAR(32),
  PASSWORD   CHAR(60),
  PRIMARY KEY (ID),
  CONSTRAINT AK_USER_NAME UNIQUE (USERNAME)
)